# Sentry information for filtering
science_queue: 31
status_queue: 0
methane_queue: 100  # for SAGE
supr_queue: 62  # for supr
mets_queue: 101  # for Mets

# USBL information for filtering
target_ids: [0, 1, 2, 5]
target_names: ["sentry", "jason", "ship", "rosette"]


# Sentry IP address : 192.168.100.226
# Sentry Listening Port : 52466
# USBL IP address : 192.168.100.226
# USBL Listening Port : 52467

# second 2 is ID in the VFR message